package workspace

import (
	"os"
	"path/filepath"

	"github.com/MakeNowJust/heredoc"
)

func createDefReadme(workName, path string) error {
	readmePath := filepath.Join(path, "README.md")
	_, err := os.Stat(readmePath)
	if !os.IsNotExist(err) {
		return nil
	}

	file, err := os.Create(readmePath)
	if err != nil {
		return err
	}

	defer file.Close()

	content := heredoc.Docf(`
		# %s

		This repo generated by Wo on %s
	`, workName, workName)

	_, err = file.WriteString(content)

	return err
}

func createLicense(workName, licenseID, path string) error {
	data, err := getLicense(licenseID)
	if err != nil {
		return err
	}
	content := compileLicense(workName, data)

	file, err := os.Create(filepath.Join(path, "LICENSE"))
	if err != nil {
		return err
	}

	defer file.Close()

	_, err = file.WriteString(content)

	return err
}
